



spring.application.name=ecom-proj
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Enable the H2 console
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true

# Optional: Change the path from /h2-console to something else
spring.h2.console.path=/h2-console

# Optional: Allow access from other machines (not just localhost)
# spring.h2.console.settings.web-allow-others=true

spring.jpa.show-sql=true
spring. jpa.hibernate.ddl-auto=update


app.upload.dir=uploads