spring.datasource.url=${jdbc:postgresql://dpg-dag9lpbl550s73adk1e0-a/shopping_db_kmzf?user=shopping_db_kmzf_user&password=6x0XhSsYB7fkJDUs4fIHNfwLtd0uYHgq}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


