spring.application.name=ecom-proj

spring.datasource.url=jdbc:postgresql://dpg-dag9lpbl550s73adk1e0-a/shopping_db_kmzf
spring.datasource.username=${shopping_db_kmzf_user}
spring.datasource.password=${6x0XhSsYB7fkJDUs4fIHNfwLtd0uYHgq}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=${PORT:8080}

app.upload.dir=uploads


